import type { Metadata } from 'next';
import { PageHero } from '@/components/layout/PageHero';
import { timeline } from '@/data/site';
import { Button } from '@/components/ui';
import { contactGroups, fmtPhone } from '@/lib/business';
export const metadata: Metadata = { title: 'About Hajibhai Valibhai', description: 'A traditional building-materials firm with a modern material library — trust, experience and expertise.' };
const values = [['Trust first', 'Honest advice, fair dealing and materials that are what we say they are.'], ['Material expertise', 'We know how stone, steel, cement and tiles behave on site, not just on paper.'], ['Service approach', 'From one tile to a full project list, we answer quickly and follow through.'], ['Modern tools', 'Visualisers, estimators and quotes online so decisions are faster and clearer.']];
export default function Page() {
  return (<><PageHero eyebrow="About" title="Traditional trust. Modern material expertise." intro="Hajibhai Valibhai is a building-materials firm built on relationships and know-how. This site is how we bring that experience online." crumbs={[{ label: 'Home', href: '/' }, { label: 'About' }]} />
    <section className="container-x pb-16 grid md:grid-cols-2 gap-5">{values.map(([t, d]) => <div key={t} className="border hairline rounded-lg p-8 bg-surface"><h2 className="font-display text-2xl">{t}</h2><p className="text-muted mt-2">{d}</p></div>)}</section>
    <section className="container-x pb-16"><h2 className="text-step-2 mb-8">Our journey</h2><ol className="border-l hairline pl-8 space-y-8 max-w-2xl">{timeline.map((t, i) => <li key={i} className="relative"><span className="absolute -left-[37px] top-2 h-3 w-3 rounded-full bg-accent" /><p className="text-accent text-sm tracking-widest">{t.year}</p><h3 className="font-display text-2xl">{t.title}</h3><p className="text-muted">{t.text}</p></li>)}</ol><p className="hint mt-6">Timeline is a placeholder — add real dates and photographs. We never publish invented numbers or certifications.</p></section>
    <section className="container-x pb-16"><h2 className="text-step-2 mb-6">Team</h2><div className="grid md:grid-cols-2 gap-5">{contactGroups.map((g) => <div key={g.title} className="border hairline rounded-lg p-8 bg-surface"><h3 className="font-display text-2xl">{g.title}</h3><p className="text-muted text-sm mt-1">For {g.note.toLowerCase()}, contact:</p><ul className="mt-5 divide-y hairline">{g.people.map((p) => <li key={p.name} className="py-3 flex items-center justify-between gap-4"><span className="font-display text-xl">{p.name}</span><span className="flex gap-2"><a className="text-accent underline underline-offset-4" href={`tel:+91${p.phone}`}>{fmtPhone(p.phone)}</a><a className="text-muted hover:text-ink" aria-label={`WhatsApp ${p.name}`} href={`https://wa.me/91${p.phone}`} target="_blank" rel="noopener noreferrer">WhatsApp</a></span></li>)}</ul></div>)}</div><div className="mt-10"><Button href="/contact/">Talk to us</Button></div></section></>);
}
